const PEOPLE_COUNT = 20;
const QUESTS_COUNT = 30;
const STAGES_COUNT = 50;
const COMMENTS_COUNT = 30;
const MAX_LIKES_COUNT = 10;
const MAX_DISLIKES_COUNT = 3;
const MAX_DONE_COUNT = 3;
const MAX_STARTED_COUNT = 10;
const MAX_QUEST_STAGES_COUNT = 10;

module.exports = {
    PEOPLE_COUNT,
    QUESTS_COUNT,
    STAGES_COUNT,
    COMMENTS_COUNT,
    MAX_LIKES_COUNT,
    MAX_DISLIKES_COUNT,
    MAX_DONE_COUNT,
    MAX_STARTED_COUNT,
    MAX_QUEST_STAGES_COUNT
};
